# Generated by Django 5.1.1 on 2024-09-28 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='answer',
            field=models.CharField(default='answer', max_length=200),
            preserve_default=False,
        ),
    ]
