# Generated by Django 4.2.16 on 2024-09-18 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='due_date',
        ),
        migrations.AddField(
            model_name='card',
            name='reviewed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
