# Generated by Django 5.1.1 on 2024-09-28 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0002_card_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='score',
        ),
    ]
