# Generated by Django 5.1.1 on 2024-10-06 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0004_alter_deck_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='repetitions',
            field=models.IntegerField(default=0),
        ),
    ]
