# Generated by Django 4.2.7 on 2023-11-26 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprogress',
            old_name='last_seen_correct',
            new_name='next_due_date',
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='last_seen_incorrect',
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='progress_status',
        ),
    ]
