# Generated by Django 4.2.7 on 2023-11-26 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0002_rename_last_seen_correct_userprogress_next_due_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprogress',
            name='last_seen',
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='next_due_date',
        ),
    ]
