# Generated by Django 4.2.7 on 2023-12-03 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0005_alter_flashcard_user_alter_userprogress_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashcard',
            name='tags',
        ),
    ]
