# Generated by Django 4.2.7 on 2023-11-26 16:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0003_remove_userprogress_last_seen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='next_due_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
